---

- name: Create configuration directory
  file:
    path: /etc/php-dns
    state: directory

- name: Upload record file
  template:
    src: "{{ php_dns_record_file }}"
    dest: /etc/php-dns/dns_records.json
    mode: 0644
    validate: 'jsonlint %s'
  notify: restart php-dns service
